name: hls4ml-tutorial-0.4.0
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyterhub
  - pydot
  - graphviz
  - pip
  - pip:
    - jupyter
    - tensorflow==2.3.1
    - hls4ml[profiling]==0.4.0
    - git+https://github.com/google/qkeras.git#egg=qkeras
