name: hls4ml-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterhub
  - pydot
  - graphviz
  - pip
  - pip:
    - jupyter
    - tensorflow==2.4.0
    - tensorflow_datasets
    - hls4ml[profiling]==0.6.0
    - qkeras==0.9.0
    - scikit-learn
    - git+https://github.com/thesps/conifer.git
